name: project CI
on: 
  workflow_dispatch: {}
  schedule:
  - cron: '0,10,20,30,40,50 * * * *'
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/global.json

    - name: Clear Nuget Cache
      run: dotnet nuget locals all --clear

    - name: Build
      run: dotnet build src/Project.sln
